// <auto-generated />
using System;
using LaboratorioPUCE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaboratorioPUCE.Migrations
{
    [DbContext(typeof(LaboratorioContext))]
    partial class LaboratorioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LaboratorioPUCE.Core.Entities.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("prestamo_id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<string>("CodigoReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo_reserva");

                    b.Property<string>("ComentarioAdmin")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("comentario_admin");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<string>("EvidenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("evidencia_url");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_devolucion");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_solicitud");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("PrestamoId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("prestamo");
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.CategoriaItem", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoria_id");

                    b.Property<byte>("EsConsumible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_consumible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaId");

                    b.ToTable("categoriaitem");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            EsConsumible = (byte)0,
                            Nombre = "Placas de Desarrollo"
                        },
                        new
                        {
                            CategoriaId = 2,
                            EsConsumible = (byte)1,
                            Nombre = "Sensores y Componentes"
                        },
                        new
                        {
                            CategoriaId = 3,
                            EsConsumible = (byte)0,
                            Nombre = "Instrumentos de Medición"
                        });
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.Espacio", b =>
                {
                    b.Property<int>("EspacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("espacio_id");

                    b.Property<byte>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<short>("Capacidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<byte>("RequiereAprobacion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requiere_aprobacion");

                    b.Property<int>("TallerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("taller_id");

                    b.Property<int>("TipoEspacioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo_espacio_id");

                    b.HasKey("EspacioId");

                    b.HasIndex("TallerId");

                    b.HasIndex("TipoEspacioId");

                    b.ToTable("espacio");

                    b.HasData(
                        new
                        {
                            EspacioId = 1,
                            Activo = (byte)1,
                            Capacidad = (short)25,
                            Descripcion = "Espacio destinado a prácticas de sistemas embebidos y circuitos.",
                            FechaCreacion = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laboratorio de Microcontroladores",
                            RequiereAprobacion = (byte)1,
                            TallerId = 1,
                            TipoEspacioId = 1
                        });
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.ItemInventario", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<byte>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoActivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo_activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<byte>("EsMaquinaria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("es_maquinaria");

                    b.Property<int>("EspacioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("espacio_id");

                    b.Property<string>("EstadoOperativo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_operativo");

                    b.Property<string>("EstadoPrestamo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("estado_prestamo");

                    b.Property<DateTime?>("FechaAdquisicion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_adquisicion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("modelo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("numero_serie");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock");

                    b.Property<int>("StockDefectuoso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock_defectuoso");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CodigoActivo")
                        .IsUnique();

                    b.HasIndex("EspacioId");

                    b.ToTable("iteminventario");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Activo = (byte)1,
                            CategoriaId = 1,
                            CodigoActivo = "DEV-ESP32-001",
                            Descripcion = "Módulo de desarrollo Wi-Fi + Bluetooth.",
                            EsMaquinaria = (byte)0,
                            EspacioId = 1,
                            EstadoOperativo = "OPERATIVO",
                            EstadoPrestamo = "DISPONIBLE",
                            FechaAdquisicion = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreacion = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Espressif",
                            Modelo = "ESP32-WROOM-32D",
                            Nombre = "Placa ESP32 NodeMCU",
                            NumeroSerie = "SN-ESP32-90812",
                            Observaciones = "Incluye cable micro USB.",
                            Stock = 1,
                            StockDefectuoso = 0
                        },
                        new
                        {
                            ItemId = 2,
                            Activo = (byte)1,
                            CategoriaId = 3,
                            CodigoActivo = "INS-MULT-001",
                            Descripcion = "Medidor de voltaje, corriente y resistencia con auto-rango.",
                            EsMaquinaria = (byte)0,
                            EspacioId = 1,
                            EstadoOperativo = "OPERATIVO",
                            EstadoPrestamo = "DISPONIBLE",
                            FechaAdquisicion = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaCreacion = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Fluke",
                            Modelo = "Fluke 115",
                            Nombre = "Multímetro Digital Profesional",
                            NumeroSerie = "SN-FLK115-4421",
                            Observaciones = "Con estuche protector.",
                            Stock = 1,
                            StockDefectuoso = 0
                        });
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol_id");

                    b.Property<byte>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<byte>("NivelAcceso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("nivel_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("RolId");

                    b.ToTable("rol");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Activo = (byte)1,
                            Descripcion = "Control operativo total y administración",
                            NivelAcceso = (byte)10,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            Activo = (byte)1,
                            Descripcion = "Consulta pública y reserva virtual",
                            NivelAcceso = (byte)1,
                            Nombre = "Estudiante"
                        });
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.SesionUsuario", b =>
                {
                    b.Property<string>("SesionId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("sesion_id");

                    b.Property<byte>("Activa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activa");

                    b.Property<DateTime>("FechaExpira")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_expira");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_origen");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("SesionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sesionusuario");
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.Taller", b =>
                {
                    b.Property<int>("TallerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("taller_id");

                    b.Property<byte>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ubicacion");

                    b.HasKey("TallerId");

                    b.ToTable("taller");

                    b.HasData(
                        new
                        {
                            TallerId = 1,
                            Activo = (byte)1,
                            Nombre = "Taller de Electrónica",
                            Ubicacion = "Edificio A - Aula 102"
                        });
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.TipoEspacio", b =>
                {
                    b.Property<int>("TipoEspacioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("tipo_espacio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<byte>("TieneInventario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tiene_inventario");

                    b.Property<byte>("TieneMaquinaria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tiene_maquinaria");

                    b.Property<byte>("TieneTickets")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tiene_tickets");

                    b.HasKey("TipoEspacioId");

                    b.ToTable("tipoespacio");

                    b.HasData(
                        new
                        {
                            TipoEspacioId = 1,
                            Nombre = "Laboratorio Físico",
                            TieneInventario = (byte)1,
                            TieneMaquinaria = (byte)1,
                            TieneTickets = (byte)1
                        });
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.Property<byte>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellido");

                    b.Property<string>("CarreraMateria")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("carrera_materia");

                    b.Property<string>("Cedula")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("cedula");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rol_id");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("TEXT")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Activo = (byte)1,
                            Apellido = "Pérez",
                            CarreraMateria = "Sistemas",
                            Cedula = "1801234567",
                            Correo = "admin@pucesa.edu.ec",
                            FechaCreacion = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            PasswordHash = "A44CA5D29F6DAB4320AB986479FA985B2D584B11A7DA934F7E80BB1449913A07",
                            RolId = 1
                        },
                        new
                        {
                            UsuarioId = 2,
                            Activo = (byte)1,
                            Apellido = "Mena",
                            CarreraMateria = "Tecnologías de la Información",
                            Cedula = "1807654321",
                            Correo = "estudiante@pucesa.edu.ec",
                            FechaCreacion = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            PasswordHash = "67D93FFBC123EC5314BD8D4779E00FB74D7F8F3D7B6A2FBC8DF7F670DB45396B",
                            RolId = 2
                        });
                });

            modelBuilder.Entity("LaboratorioPUCE.Core.Entities.Prestamo", b =>
                {
                    b.HasOne("LaboratorioPUCE.Models.ItemInventario", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratorioPUCE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.Espacio", b =>
                {
                    b.HasOne("LaboratorioPUCE.Models.Taller", "Taller")
                        .WithMany()
                        .HasForeignKey("TallerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratorioPUCE.Models.TipoEspacio", "TipoEspacio")
                        .WithMany()
                        .HasForeignKey("TipoEspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taller");

                    b.Navigation("TipoEspacio");
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.ItemInventario", b =>
                {
                    b.HasOne("LaboratorioPUCE.Models.CategoriaItem", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratorioPUCE.Models.Espacio", "Espacio")
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Espacio");
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.SesionUsuario", b =>
                {
                    b.HasOne("LaboratorioPUCE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.Usuario", b =>
                {
                    b.HasOne("LaboratorioPUCE.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LaboratorioPUCE.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
